export const SET_STATE = "SET_STATE"
export const TOGGLE_SETTINGS_MENU = "TOGGLE_SETTINGS_MENU"
export const TOGGLE_RULES_MENU = "TOGGLE_RULES_MENU"
export const TOGGLE_SHOE_EMPTY_MENU = "TOGGLE_SHOE_EMPTY_MENU"
export const TOGGLE_ADD_FUNDS_MENU = "TOGGLE_ADD_FUNDS_MENU"
export const SET_SETTING = "SET_SETTING"
export const RESET_SETTINGS = "RESET_SETTINGS"
export const SET_SHOE = "SET_SHOE"
export const SET_BET = "SET_BET"
export const DEAL_HANDS = 'DEAL_HANDS'
export const DRAW_CARD = "DRAW_CARD"

export const SET_DEALER_INITIAL = "SET_DEALER_INITIAL"
export const SET_PLAYER_INITIAL = "SET_PLAYER_INITIAL"

export const HANDLE_DEALER_ACE = "HANDLE_DEALER_ACE"

export const HANDLE_EVEN_MONEY = "HANDLE_EVEN_MONEY"
export const HANDLE_INSURANCE = "HANDLE_INSURANCE"

export const PLAYER_HIT = "PLAYER_HIT"
export const PLAYER_DOUBLE_DOWN = "PLAYER_DOUBLE_DOWN"
export const PLAYER_STAY = "PLAYER_STAY"
export const DEALER_HIT = "DEALER_HIT"
export const DETERMINE_WINNER = "DETERMINE_WINNER"

export const ADD_FUNDS = 'ADD_FUNDS'


export const PLAYER_WIN = "PLAYER_WIN"
export const DEALER_WIN = "DEALER_WIN"
export const PLAYER_BLACKJACK = "PLAYER_BLACKJACK"
export const DEALER_BLACKJACK = "DEALER_BLACKJACK"
export const PLAYER_INSURANCE_PAYOUT = "PLAYER_INSURANCE_PAYOUT"
export const PLAYER_EVEN_MONEY_PAYOUT = "PLAYER_EVEN_MONEY_PAYOUT"
export const PLAYER_PUSH = "PLAYER_PUSH"
export const SHOW_RESULTS = "SHOW_RESULTS"

export const SET_PLAYER_TURN = "SET_PLAYER_TURN"
export const SPLIT_HANDS = "SPLIT_HANDS"
export const PLAY_NEXT_SPLIT = "PLAY_NEXT_SPLIT"
export const SET_DEALER_TURN = "SET_DEALER_TURN"

export const SHOW_BOOK_MOVE = "SHOW_BOOK_MOVE"